# Generated by Django 6.0.1 on 2026-01-21 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['to_user', '-created_at'], name='reviews_rev_to_user_df5dff_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['from_user', '-created_at'], name='reviews_rev_from_us_b69141_idx'),
        ),
    ]
