# Generated by Django 5.0.14 on 2026-02-09 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "registration_id",
                    models.CharField(
                        help_text="Firebase Cloud Messaging registration token",
                        max_length=255,
                        unique=True,
                        verbose_name="FCM Token",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        default="android",
                        max_length=20,
                        verbose_name="Device Type",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive devices are skipped",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ["-last_used_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "active"], name="notificatio_user_id_155101_idx"
                    ),
                    models.Index(
                        fields=["registration_id"],
                        name="notificatio_registr_e800af_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom data payload for the notification",
                        verbose_name="Data",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Read")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="notificatio_created_ae6ed6_idx"
                    ),
                ],
            },
        ),
    ]
