# Generated by Django 6.0.1 on 2026-01-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified account (trusted reviews)'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews received'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last rating update timestamp', null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-rating'], name='users_user_rating_4beaf5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', '-rating'], name='users_user_role_69084c_idx'),
        ),
    ]
