# Generated by Django 6.0.1 on 2026-01-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skill_workerprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='passport_scan_back',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='passport_scan_front',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='passport_series',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='bank_card_number',
            field=models.CharField(blank=True, help_text='Bank card number', max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name', max_length=100),
        ),
    ]
