# Generated by Django 5.0.14 on 2026-02-09 16:34

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        max_length=128,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                ("code", models.CharField(max_length=6, verbose_name="OTP Code")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                ("is_used", models.BooleanField(default=False, verbose_name="Is Used")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="individualprofile",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="businessprofile",
            options={
                "verbose_name": "Business Profile",
                "verbose_name_plural": "Business Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="workerprofile",
            options={
                "verbose_name": "Worker Profile",
                "verbose_name_plural": "Worker Profiles",
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email",
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="documents",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of document objects: [{type, url, uploaded_at}]",
                verbose_name="Documents",
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="locations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of location objects: [{address, lat, lng, name}]",
                verbose_name="Locations",
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="verification_notes",
            field=models.TextField(blank=True, verbose_name="Admin Verification Notes"),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("pending", "Pending Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="unverified",
                max_length=20,
                verbose_name="Verification Status",
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="completed_jobs_count",
            field=models.IntegerField(default=0, verbose_name="Completed Jobs Count"),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="experience",
            field=models.TextField(
                blank=True,
                help_text="Text description of work experience",
                verbose_name="Experience",
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="payment_account_id",
            field=models.CharField(
                blank=True,
                help_text="ID from payment service provider for payouts",
                max_length=255,
                verbose_name="Payment Account ID",
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="workers/photos/",
                verbose_name="Photo (Selfie)",
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Average rating from 0.00 to 5.00",
                max_digits=3,
                verbose_name="Rating",
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="skills",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Array of skill tags, e.g., ["waiter", "courier"]',
                verbose_name="Skills",
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("pending", "Pending Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="unverified",
                max_length=20,
                verbose_name="Verification Status",
            ),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="bin",
            field=models.CharField(
                help_text="Business Identification Number",
                max_length=20,
                unique=True,
                verbose_name="BIN",
            ),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="company_name",
            field=models.CharField(max_length=255, verbose_name="Company Name"),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="contact_name",
            field=models.CharField(max_length=255, verbose_name="Contact Person Name"),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="contact_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Contact Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="inn",
            field=models.CharField(
                help_text="Individual Identification Number",
                max_length=20,
                unique=True,
                verbose_name="INN",
            ),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="legal_address",
            field=models.TextField(verbose_name="Legal Address"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("worker", "Worker"),
                    ("business", "Business"),
                    ("admin", "Admin"),
                ],
                max_length=20,
                verbose_name="User Type",
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Full Name"),
        ),
        migrations.AddIndex(
            model_name="businessprofile",
            index=models.Index(
                fields=["verification_status"], name="users_busin_verific_e52de4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessprofile",
            index=models.Index(
                fields=["company_name"], name="users_busin_company_0eb095_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["phone"], name="users_custo_phone_ad7713_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["user_type"], name="users_custo_user_ty_f25e6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workerprofile",
            index=models.Index(
                fields=["verification_status"], name="users_worke_verific_41e547_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workerprofile",
            index=models.Index(
                fields=["-rating"], name="users_worke_rating_bf2166_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["phone", "-created_at"], name="users_otp_phone_d158be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["code", "phone"], name="users_otp_code_48d871_idx"
            ),
        ),
        migrations.DeleteModel(
            name="IndividualProfile",
        ),
    ]
