# Generated by Django 5.0.14 on 2026-02-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_otp_remove_individualprofile_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[],
            options={
                "verbose_name": "System Statistic",
                "verbose_name_plural": "System Statistics",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
        ),
    ]
