# Generated by Django 5.0.14 on 2026-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_statistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=3, verbose_name="Rating"
            ),
        ),
    ]
