# Generated by Django 5.0.14 on 2026-02-09 16:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("waiter", "Waiter"),
                            ("courier", "Courier"),
                            ("loader", "Loader"),
                            ("cleaner", "Cleaner"),
                            ("cashier", "Cashier"),
                            ("bartender", "Bartender"),
                            ("cook", "Cook"),
                            ("security", "Security Guard"),
                            ("promoter", "Promoter"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Job Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short descriptive title",
                        max_length=255,
                        verbose_name="Job Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed job description and requirements",
                        verbose_name="Description",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment per hour in local currency",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Hourly Rate",
                    ),
                ),
                (
                    "workers_needed",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Workers Needed",
                    ),
                ),
                (
                    "workers_accepted",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Workers Accepted"
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        help_text='e.g., "Main Office", "Restaurant Branch 1"',
                        max_length=255,
                        verbose_name="Location Name",
                    ),
                ),
                (
                    "location_address",
                    models.CharField(max_length=500, verbose_name="Address"),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitude"
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitude"
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        help_text="Skills, experience, or other requirements",
                        verbose_name="Requirements",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "business"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from worker to business",
                        verbose_name="Application Message",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                        verbose_name="Job",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "worker"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(verbose_name="Checked In At")),
                (
                    "check_in_lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Check-in Latitude"
                    ),
                ),
                (
                    "check_in_lng",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="Check-in Longitude",
                    ),
                ),
                (
                    "checked_out_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Checked Out At"
                    ),
                ),
                (
                    "check_out_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Check-out Latitude",
                    ),
                ),
                (
                    "check_out_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Check-out Longitude",
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Device metadata for anti-fraud",
                        verbose_name="Device Info",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin",
                        to="jobs.jobapplication",
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Check-in",
                "verbose_name_plural": "Check-ins",
                "ordering": ["-checked_in_at"],
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "-created_at"], name="jobs_job_status_57b86b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["business", "status"], name="jobs_job_busines_3fdc0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["date", "start_time"], name="jobs_job_date_3ae85a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["location_lat", "location_lng"],
                name="jobs_job_locatio_4b565d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_type", "status"], name="jobs_job_job_typ_3f135c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["job", "status"], name="jobs_jobapp_job_id_08192b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["worker", "status"], name="jobs_jobapp_worker__3d76bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["-applied_at"], name="jobs_jobapp_applied_ab7064_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("job", "worker")},
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["-checked_in_at"], name="jobs_checki_checked_a5d3b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["application"], name="jobs_checki_applica_e3d66c_idx"
            ),
        ),
    ]
