# Generated by Django 5.0.14 on 2026-02-09 16:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total transaction amount",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Commission charged by platform",
                        max_digits=10,
                        verbose_name="Platform Fee",
                    ),
                ),
                (
                    "worker_payout",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Net amount paid to worker",
                        max_digits=10,
                        verbose_name="Worker Payout",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("held", "Held in Escrow"),
                            ("completed", "Completed"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="PSP payment intent identifier",
                        max_length=255,
                        verbose_name="Payment Intent ID",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Unique key to prevent duplicate transactions",
                        max_length=255,
                        unique=True,
                        verbose_name="Idempotency Key",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional transaction data",
                        verbose_name="Metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "business"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Business (Payer)",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="jobs.job",
                        verbose_name="Job",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "worker"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Worker (Payee)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Payout Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "transfer_id",
                    models.CharField(
                        blank=True,
                        help_text="PSP transfer identifier",
                        max_length=255,
                        verbose_name="Transfer ID",
                    ),
                ),
                (
                    "destination_account",
                    models.CharField(
                        blank=True,
                        help_text="Worker payment account ID",
                        max_length=255,
                        verbose_name="Destination Account",
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Failure Reason"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="Retry Count"),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "worker",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "worker"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Worker",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="payments.transaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payout",
                "verbose_name_plural": "Payouts",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="Escrow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "held_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Held Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held"),
                            ("released", "Released"),
                            ("refunded", "Refunded"),
                        ],
                        default="held",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("held_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auto_release_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Hours after checkout to auto-release funds",
                        verbose_name="Auto-release Hours",
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow",
                        to="jobs.jobapplication",
                        verbose_name="Job Application",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow",
                        to="payments.transaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escrow",
                "verbose_name_plural": "Escrows",
                "ordering": ["-held_at"],
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_tr_status_7127e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["business", "-created_at"],
                name="payments_tr_busines_7c79b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["worker", "-created_at"], name="payments_tr_worker__9a46b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["idempotency_key"], name="payments_tr_idempot_801f50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                fields=["status", "-initiated_at"], name="payments_pa_status_1bae9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                fields=["worker", "-initiated_at"],
                name="payments_pa_worker__8ad444_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(
                fields=["status", "-held_at"], name="payments_es_status_6afde1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(
                fields=["application"], name="payments_es_applica_9d1eb2_idx"
            ),
        ),
    ]
