# Generated by Django 6.0.1 on 2026-01-21 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency_weight', models.DecimalField(decimal_places=2, default=0.3, help_text='Weight for recent reviews (0-1)', max_digits=3)),
                ('verified_user_weight', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for verified user reviews', max_digits=3)),
                ('min_review_interval_minutes', models.PositiveIntegerField(default=60, help_text='Minimum minutes between reviews from same user')),
                ('max_reviews_per_day', models.PositiveIntegerField(default=10, help_text='Maximum reviews a user can give per day')),
                ('new_account_days', models.PositiveIntegerField(default=7, help_text="Days after which account is no longer 'new'")),
                ('circular_rating_check_depth', models.PositiveIntegerField(default=3, help_text='Depth for detecting circular rating patterns')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rating Configuration',
                'verbose_name_plural': 'Rating Configuration',
            },
        ),
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('new_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('old_count', models.PositiveIntegerField(default=0)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(choices=[('review_added', 'Review Added'), ('review_updated', 'Review Updated'), ('review_deleted', 'Review Deleted'), ('fraud_detected', 'Fraud Detected'), ('admin_adjustment', 'Admin Adjustment'), ('recalculation', 'Periodic Recalculation')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_changes_made', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_changes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating History',
                'verbose_name_plural': 'Rating Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ratings_rat_user_id_7443d3_idx'), models.Index(fields=['reason'], name='ratings_rat_reason_ac47c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RatingProtectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('rate_limit', 'Rate Limit Exceeded'), ('pattern_detected', 'Suspicious Pattern Detected'), ('ip_duplicate', 'Duplicate IP Address'), ('circular_rating', 'Circular Rating Attempt'), ('new_account_spam', 'New Account Spam'), ('suspicious_timing', 'Suspicious Timing Pattern')], max_length=30)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_target_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fraud Protection Log',
                'verbose_name_plural': 'Fraud Protection Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ratings_rat_user_id_730e2f_idx'), models.Index(fields=['action_type'], name='ratings_rat_action__75d21c_idx'), models.Index(fields=['ip_address'], name='ratings_rat_ip_addr_bbd1c5_idx'), models.Index(fields=['blocked'], name='ratings_rat_blocked_0b1787_idx')],
            },
        ),
    ]
